apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "19101"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: sealos-nm-agent
    app.kubernetes.io/part-of: sealos-nm
    k8s-app: sealos-nm-agent
  name: sealos-nm-agent
  namespace: sealos-networkmanager-system
spec:
  clusterIP: None
  ports:
  - name: agent-metrics
    port: 19101
    protocol: TCP
    targetPort: agent-metrics
  selector:
    k8s-app: sealos-nm-agent
  type: ClusterIP
